import { useCallback, useEffect, useState } from 'react';
import { LoaderCircle, Trash2, UserPlus } from 'lucide-react';
import api from '../services/api';

export default function AdminAccounts() {
  const [admins, setAdmins] = useState([]); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [creating, setCreating] = useState(false); const [deletingId, setDeletingId] = useState(null);
  const load = useCallback(async (attempt = 0) => { setLoading(true); try { const { data } = await api.get('/admins'); setAdmins(data); } catch { if (attempt === 0) { window.setTimeout(() => load(1), 350); return; } setMessage('Unable to load admin accounts.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const create = async (event) => { event.preventDefault(); if (creating) return; setCreating(true); setMessage(''); try { await api.post('/admins', form); setForm({ name: '', email: '', password: '' }); setMessage('Admin account created.'); await load(); } catch (error) { setMessage(error.response?.data?.message || 'Unable to create admin.'); } finally { setCreating(false); } };
  const remove = async (id) => { if (deletingId || !window.confirm('Remove this admin account?')) return; setDeletingId(id); setMessage(''); try { await api.delete(`/admins/${id}`); setAdmins((current) => current.filter((admin) => admin._id !== id && admin.id !== id)); setMessage('Admin account removed.'); } catch (error) { setMessage(error.response?.data?.message || 'Unable to remove admin.'); } finally { setDeletingId(null); } };
  return <div className="mx-auto max-w-5xl space-y-6 pb-10"><section className="glass-panel rounded-3xl p-6"><h1 className="text-2xl font-bold text-white">Admin accounts</h1><p className="text-sm text-white/50">Training Commander-only account management.</p><form onSubmit={create} className="mt-5 grid gap-3 md:grid-cols-4"><input data-testid="admin-name" required disabled={creating} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Name" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-white" /><input data-testid="admin-email" required disabled={creating} type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="Email" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-white" /><input data-testid="admin-password" required disabled={creating} minLength="8" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="Password" className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-white" /><button data-testid="create-admin" disabled={creating} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-gold px-3 py-2 font-bold text-darkGreen transition active:scale-[.98] disabled:cursor-not-allowed disabled:opacity-60">{creating ? <LoaderCircle size={16} className="animate-spin" /> : <UserPlus size={16} />}{creating ? 'Creating...' : 'Add admin'}</button></form>{message && <p data-testid="admin-message" className="mt-3 text-sm text-white/80">{message}</p>}</section><div className="space-y-2">{loading ? <p className="glass-panel rounded-2xl p-5 text-white/50">Loading admin accounts...</p> : admins.map((admin) => <div key={admin._id || admin.id} className="glass-panel flex items-center justify-between rounded-2xl p-4"><div><p className="font-semibold text-white">{admin.name}</p><p className="text-sm text-white/50">{admin.email}</p></div><button disabled={Boolean(deletingId)} onClick={() => remove(admin._id || admin.id)} className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-lg p-2 text-red-300 transition hover:bg-red-400/10 active:scale-95 disabled:cursor-not-allowed disabled:opacity-60" aria-label={`Remove ${admin.name}`}>{deletingId === (admin._id || admin.id) ? <LoaderCircle size={18} className="animate-spin" /> : <Trash2 size={18} />}</button></div>)}</div></div>;
}
