import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Activity, Award, CalendarDays, ClipboardCheck, Dumbbell } from 'lucide-react';
import api from '../services/api';
import SubjectCard from '../components/SubjectCard';
import VideoUpload from '../components/VideoUpload';

const Metric = ({ icon: Icon, label, value }) => <div className="rounded-2xl border border-white/10 bg-black/20 p-4"><Icon size={20} className="text-gold" /><p className="mt-3 text-2xl font-bold text-white">{value}</p><p className="text-sm text-white/50">{label}</p></div>;

export default function CadetDashboardFull() {
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await api.get('/dashboard/cadet'); setData(response.data); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load your dashboard.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const stats = data?.stats || {};
  if (loading) return <div className="mx-auto max-w-6xl space-y-6 pb-10"><div className="glass-panel h-44 animate-pulse rounded-3xl bg-white/[0.02]" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <div key={index} className="glass-panel h-28 animate-pulse rounded-2xl bg-white/[0.02]" />)}</div></div>;
  return <div className="mx-auto max-w-6xl space-y-7 pb-10"><section className="glass-panel rounded-3xl p-7"><p className="text-sm font-semibold uppercase tracking-wider text-gold">Cadet portal</p><h1 className="mt-2 text-3xl font-bold text-white">Your training progress</h1><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Activity} label="Overall attendance" value={`${stats.attendance_percentage ?? 0}%`} /><Metric icon={ClipboardCheck} label="Sessions attended" value={`${stats.present_sessions ?? 0}/${stats.total_sessions ?? 0}`} /><Metric icon={Award} label="Academic average" value={`${stats.average_mark_percentage ?? 0}%`} /><Metric icon={Dumbbell} label="Physicals accepted" value={`${stats.accepted_submissions ?? 0}/${stats.total_submissions ?? 0}`} /></div></section>{error && <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-red-200"><span>{error}</span><button type="button" onClick={load} className="rounded-lg border border-red-300/30 px-3 py-1.5 text-sm font-semibold">Retry</button></div>}<section><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold text-white">Subject attendance</h2><div className="flex gap-3"><Link className="text-sm text-gold hover:text-white" to="/attendance">View history</Link><Link className="text-sm text-gold hover:text-white" to="/academics">Academic history</Link></div></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{data?.subjectAttendance?.map((subject) => <SubjectCard key={subject.subject_id} subjectName={subject.name} present={subject.present_count} absent={subject.absent_count} total={subject.total_sessions} />)}</div>{data && !data.subjectAttendance.length && <p className="glass-panel rounded-2xl p-8 text-center text-white/50">No subjects are assigned yet.</p>}</section><section className="glass-panel flex flex-wrap items-center justify-between gap-4 rounded-3xl p-5"><div><h2 className="font-bold text-white">Physical-training status</h2><p className="mt-1 text-sm text-white/50">{stats.pending_submissions ?? 0} submission(s) awaiting review.</p></div><Link to="/physical" className="inline-flex items-center gap-2 rounded-xl border border-gold/30 px-4 py-2 text-sm font-bold text-gold hover:bg-gold/10"><CalendarDays size={16} />View submission history</Link></section><VideoUpload onUploaded={load} /></div>;
}
