import { useCallback, useEffect, useState } from 'react';
import { BarChart3, UserRound } from 'lucide-react';
import api from '../services/api';

const Metric = ({ label, value }) => <div className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-2xl font-bold text-white">{value}</p><p className="mt-1 text-sm text-white/50">{label}</p></div>;

export default function ReportsFull() {
  const [report, setReport] = useState(null);
  const [cadets, setCadets] = useState([]);
  const [selectedCadet, setSelectedCadet] = useState('');
  const [cadetReport, setCadetReport] = useState(null);
  const [error, setError] = useState('');
  const [loadingCadet, setLoadingCadet] = useState(false);
  const load = useCallback(async () => { setError(''); try { const [overview, cadetList] = await Promise.all([api.get('/reports/overview'), api.get('/cadets')]); setReport(overview.data); setCadets(cadetList.data); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load reports.'); } }, []);
  useEffect(() => { load(); }, [load]);
  const loadCadetReport = async (id) => { setSelectedCadet(id); setCadetReport(null); if (!id) return; setLoadingCadet(true); try { setCadetReport((await api.get(`/reports/cadet/${id}`)).data); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load the cadet report.'); } finally { setLoadingCadet(false); } };
  if (error && !report) return <p className="rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-red-200">{error}</p>;
  if (!report) return <p className="glass-panel rounded-3xl p-8 text-center text-white/50">Loading reports...</p>;
  const stats = report.stats;
  return <div className="mx-auto max-w-6xl space-y-6 pb-10"><section className="glass-panel rounded-3xl p-6"><div className="flex items-center gap-3"><BarChart3 className="text-gold" /><div><h1 className="text-2xl font-bold text-white">Operational reports</h1><p className="text-sm text-white/50">Live totals from Supabase PostgreSQL.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Cadets" value={stats.total_cadets} /><Metric label="Active admins" value={stats.active_admins} /><Metric label="Attendance" value={`${stats.overall_attendance_percentage}%`} /><Metric label="Pending physical reviews" value={stats.pending_physical_reviews} /><Metric label="Assessments" value={stats.total_assessments} /></div></section><section className="glass-panel rounded-3xl p-6"><div className="flex items-center gap-2"><UserRound size={18} className="text-gold" /><h2 className="font-bold text-white">Individual cadet report</h2></div><select value={selectedCadet} onChange={(event) => loadCadetReport(event.target.value)} className="field mt-4 max-w-md"><option value="">Select a cadet</option>{cadets.map((cadet) => <option key={cadet.id} value={cadet.id}>{cadet.name} · {cadet.email}</option>)}</select>{loadingCadet && <p className="mt-4 text-sm text-white/50">Loading cadet report...</p>}{cadetReport && <div className="mt-5"><p className="font-semibold text-white">{cadetReport.cadet.name}</p><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Attendance" value={`${cadetReport.attendance.percentage}%`} /><Metric label="Present / sessions" value={`${cadetReport.attendance.present}/${cadetReport.attendance.total}`} /><Metric label="Assessments" value={cadetReport.marks.total} /><Metric label="Physicals accepted" value={`${cadetReport.physicals.accepted}/${cadetReport.physicals.total}`} /></div></div>}</section><section className="glass-panel rounded-3xl p-6"><h2 className="font-bold text-white">Subject attendance</h2><div className="mt-4 space-y-3">{report.subjectWiseAttendance.map((item) => <div key={item.subject_id}><div className="flex justify-between text-sm"><span className="text-white">{item.name}</span><span className="text-gold">{item.percentage}%</span></div><div className="mt-1 h-2 rounded-full bg-white/10"><div className="h-2 rounded-full bg-gold" style={{ width: `${item.percentage}%` }} /></div></div>)}</div></section>{error && <p className="rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-red-200">{error}</p>}</div>;
}
